// Generated from tools/plugin-contract/contract/capabilities.json. Do not edit.
//
// A capability page without a manifest entry fails `npm run check:nav`, so this
// is generated beside the pages rather than kept by hand.

import type { NavGroupDef } from './nav-structure';

export const pluginCapabilityNav: NavGroupDef[] = [
  {
    group: 'Capabilities',
    pages: [
      'capabilities',
      'capabilities/network-fetch',
      'capabilities/network-dial',
      'capabilities/network-listen',
      'capabilities/network-discover',
      'capabilities/storage-private',
      'capabilities/storage-path',
      'capabilities/storage-temp',
      'capabilities/storage-derived',
      'capabilities/library-read',
      'capabilities/library-write',
      'capabilities/library-import',
      'capabilities/library-watch',
      'capabilities/metadata-query',
      'capabilities/metadata-provide',
      'capabilities/media-source',
      'capabilities/media-proxy',
      'capabilities/media-live',
      'capabilities/media-transcode',
      'capabilities/media-remux',
      'capabilities/media-record',
      'capabilities/encoder-profile',
      'capabilities/encoder-dispatch',
      'capabilities/jobs-dispatch',
      'capabilities/jobs-status',
      'capabilities/scheduler',
      'capabilities/audio-tools',
      'capabilities/music-analysis-read',
      'capabilities/music-analysis-write',
      'capabilities/player-source',
      'capabilities/player-control',
      'capabilities/player-state',
      'capabilities/player-queue',
      'capabilities/cast-send',
      'capabilities/user-identity',
      'capabilities/user-watch',
      'capabilities/user-playlists',
      'capabilities/user-preferences',
      'capabilities/users-list',
      'capabilities/notifications-push',
      'capabilities/secrets',
      'capabilities/settings',
      'capabilities/events-subscribe',
      'capabilities/events-publish',
      'capabilities/hub',
      'capabilities/rest',
      'capabilities/auth-claims',
      'capabilities/process-spawn',
      'capabilities/browser-headless',
      'capabilities/native-code',
      'capabilities/server-info',
      'capabilities/ui-mount',
      'capabilities/ui-input',
      'capabilities/ui-webview',
      'capabilities/ui-overlay',
    ],
  },
];
