// Generated by tools/nm-components. Do not edit.
//
// The docs build fails if a page is missing here or named here without a
// file, so this is generated from the same manifest the pages are.

import type { NavGroupDef } from './nav-structure';

export const nmComponentsNav: NavGroupDef[] = [
  { group: "Getting Started", pages: ['overview', 'box', 'payloads', 'theming', 'dashboards'] },
  { group: "Atoms", pages: ['components/avatar', 'components/badge', 'components/divider', 'components/form-label', 'components/helper', 'components/image', 'components/link', 'components/progress', 'components/skeleton', 'components/spinner', 'components/tag'] },
  { group: "Controls", pages: ['components/button', 'components/checkbox', 'components/input', 'components/radio', 'components/rating', 'components/slider', 'components/textarea', 'components/toggle'] },
  { group: "Groups", pages: ['components/badge-group', 'components/breadcrumb', 'components/button-group', 'components/checkbox-group', 'components/pagination', 'components/radio-group', 'components/segmented', 'components/step-indicator', 'components/toggles'] },
  { group: "Surfaces", pages: ['components/alert', 'components/card', 'components/chat', 'components/content-footer', 'components/content-header', 'components/empty-state', 'components/list', 'components/metrics', 'components/table'] },
  { group: "Overlays", pages: ['components/color-picker', 'components/combobox', 'components/command-palette', 'components/date-picker', 'components/drawer', 'components/dropdown', 'components/modal', 'components/popover', 'components/search-input', 'components/select', 'components/toast', 'components/tooltip'] },
  { group: "Structures", pages: ['components/accordion', 'components/carousel', 'components/file-upload', 'components/navigation', 'components/stepper', 'components/tabs', 'components/tree-view'] },
];
